# Model arguments
model_name_or_path: google/gemma-2-9b-it
torch_dtype: null
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  simonycl/gemma2-9B-it-ultrafeedback-armorm-judge: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# SimPOTrainer arguments
bf16: true
beta: 0.01
do_eval: true
eval_strategy: steps
eval_steps: 400
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: dpo-gemma2-9b-agg-judge-no-special
learning_rate: 5.0e-7
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 4096
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
output_dir: outputs/gemma2-9b-agg-judge-no-special
run_name: gemma2-9b-agg-judge-no-special
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
report_to:
- wandb
save_total_limit: 20
seed: 42
warmup_ratio: 0.1